# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CrowdLaw Manifesto
email: admin@thegovlab.org
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manifesto.crowd.law/" # the base hostname & protocol for your site
twitter_username: govlab
github_username:  GovLab

# Build settings
markdown: kramdown
# theme: minima

# page_gen:
#   - data: companies
#     name: company_name_id
#     template: company-page

contentful:
  spaces:
    - entries: # Jekyll _data folder identifier - Required
        space: h96qvckp021n         # Required
        access_token: 75985f7c583124647e5905e7ff6b1e945a6faccf7c8fcc995cd87ee732b3c6e2
        # base_path:         # Optional - Defaults to Current directory
        # destination: ./source/_data/contentful/spaces # Optional - Defaults to _data/contentful/spaces
        all_entries: true


exclude: [node_modules, gulpfile.js]
# include: [_data]

sass:
  style: compressed

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "es"]
exclude_from_localizations: ["javascript", "images", "css"]